cmake_minimum_required(VERSION 3.24)

function(pkg_message lvl msg)
    message(${lvl} "PkgInstall [${pkg_name}]: ${msg} ${ARGN}")
endfunction()

macro(pkg_set var val)
    set(${var} ${val} ${ARGN})
    set(${var} ${val} ${ARGN} PARENT_SCOPE)
    mark_as_advanced(${var})
endmacro()

function(pkg_sync_cache_list var help)
    set(merged_values)
    if(DEFINED ${var} AND NOT "${${var}}" STREQUAL "")
        list(APPEND merged_values ${${var}})
    endif()

    get_property(cache_entry_exists CACHE "${var}" PROPERTY VALUE SET)
    if(cache_entry_exists)
        get_property(cache_value CACHE "${var}" PROPERTY VALUE)
        if(NOT "${cache_value}" STREQUAL "")
            list(APPEND merged_values ${cache_value})
        endif()
    endif()

    list(REMOVE_DUPLICATES merged_values)
    set(${var} "${merged_values}" PARENT_SCOPE)
    set(${var} "${merged_values}" CACHE INTERNAL "${help}" FORCE)
endfunction()

function(pkg_is_valid_package_dir_var out_var var)
    set(${out_var} FALSE PARENT_SCOPE)
    if(NOT DEFINED ${var})
        return()
    endif()

    if(var MATCHES "^(CMAKE|PROJECT)_" OR var MATCHES "(_SOURCE_DIR|_BINARY_DIR)$")
        return()
    endif()

    set(value "${${var}}")
    string(STRIP "${value}" value)
    if(value STREQUAL "" OR value MATCHES "-NOTFOUND$")
        return()
    endif()

    if(NOT IS_DIRECTORY "${value}")
        return()
    endif()

    file(GLOB config_files LIST_DIRECTORIES FALSE
         "${value}/*Config.cmake"
         "${value}/*-config.cmake")
    if(config_files)
        set(${out_var} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(pkg_get_lock_file out_var)
    if(DEFINED ENV{HOME})
        set(lock_root "$ENV{HOME}/.cache/cmake-pkginstall")
    elseif(DEFINED ENV{USERPROFILE})
        set(lock_root "$ENV{USERPROFILE}/.cache/cmake-pkginstall")
    else()
        set(lock_root "${CMAKE_BINARY_DIR}/CMakeFiles")
    endif()
    file(MAKE_DIRECTORY "${lock_root}")
    string(SHA256 source_hash "${CMAKE_SOURCE_DIR}")
    set(${out_var} "${lock_root}/${PROJECT_NAME}-${source_hash}.lock" PARENT_SCOPE)
endfunction()

function(pkg_get_manifest_file out_var pkg_name install_dir)
    set(${out_var} "${install_dir}/.pkg_install_success_${pkg_name}.cmake" PARENT_SCOPE)
endfunction()

function(pkg_compute_fingerprint out_var pkg_name pkg_version install_dir pkg_cmake_args)
    list(JOIN pkg_cmake_args "\n" pkg_args_string)
    string(JOIN "\n" fingerprint_input
            "pkg_name=${pkg_name}"
            "pkg_version=${pkg_version}"
            "install_dir=${install_dir}"
            "generator=${CMAKE_GENERATOR}"
            "build_type=${CMAKE_BUILD_TYPE}"
            "c_compiler=${CMAKE_C_COMPILER}"
            "cxx_compiler=${CMAKE_CXX_COMPILER}"
            "fortran_compiler=${CMAKE_Fortran_COMPILER}"
            "shared_libs=${BUILD_SHARED_LIBS}"
            "pkg_cmake_args=${pkg_args_string}")
    string(SHA256 fingerprint "${fingerprint_input}")
    set(${out_var} "${fingerprint}" PARENT_SCOPE)
endfunction()

function(pkg_manifest_matches out_var manifest_file expected_fingerprint)
    set(${out_var} FALSE PARENT_SCOPE)
    if(NOT EXISTS "${manifest_file}")
        return()
    endif()

    unset(PKG_MANIFEST_FINGERPRINT)
    include("${manifest_file}" OPTIONAL RESULT_VARIABLE manifest_loaded)
    if(NOT manifest_loaded)
        return()
    endif()

    if(DEFINED PKG_MANIFEST_FINGERPRINT AND PKG_MANIFEST_FINGERPRINT STREQUAL expected_fingerprint)
        set(${out_var} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(pkg_manifest_append_set manifest_file key value)
    file(APPEND "${manifest_file}" "set(${key} [==[${value}]==])\n")
endfunction()

function(pkg_write_manifest manifest_file pkg_name pkg_version install_dir fingerprint pkg_cmake_args)
    list(JOIN pkg_cmake_args "\n" pkg_args_string)
    file(WRITE "${manifest_file}" "# Auto-generated by pkg_install()\n")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_NAME "${pkg_name}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_VERSION "${pkg_version}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_INSTALL_DIR "${install_dir}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_GENERATOR "${CMAKE_GENERATOR}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_BUILD_TYPE "${CMAKE_BUILD_TYPE}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_C_COMPILER "${CMAKE_C_COMPILER}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_CXX_COMPILER "${CMAKE_CXX_COMPILER}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_Fortran_COMPILER "${CMAKE_Fortran_COMPILER}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_SHARED_LIBS "${BUILD_SHARED_LIBS}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_CMAKE_ARGS "${pkg_args_string}")
    pkg_manifest_append_set("${manifest_file}" PKG_MANIFEST_FINGERPRINT "${fingerprint}")
endfunction()

# Dumps cached variables to PKG_INIT_CACHE_FILE so that we can propagate
# the current build configuration to dependencies
function(generate_init_cache)
    set(PKG_INIT_CACHE_FILE ${CMAKE_BINARY_DIR}/CMakeFiles/CMakeTmp/init-cache.cmake)
    set(PKG_INIT_CACHE_FILE ${PKG_INIT_CACHE_FILE} PARENT_SCOPE)
    file(WRITE  ${PKG_INIT_CACHE_FILE} "# These variables will initialize the CMake cache for subprocesses.\n")
    get_cmake_property(vars CACHE_VARIABLES)
    foreach(var ${vars})
        if(var MATCHES "CMAKE_CACHE|CMAKE_HOME|CMAKE_EXTRA|CMAKE_PROJECT|MACRO")
            continue()
        endif()
        get_property(help CACHE "${var}" PROPERTY HELPSTRING)
        get_property(type CACHE "${var}" PROPERTY TYPE)
        string(REPLACE "\\" "/" ${var} "${${var}}") # Fix windows backslash paths
        string(REPLACE "\"" "\\\"" help "${help}") #Fix quotes on some cuda-related descriptions
        string(REPLACE "\"" "\\\"" ${var} "${${var}}") #Fix quotes
        file(APPEND ${PKG_INIT_CACHE_FILE} "set(${var} \"${${var}}\" CACHE ${type} \"${help}\" FORCE)\n")
    endforeach()

    get_cmake_property(live_vars VARIABLES)
    foreach(var ${live_vars})
        if(NOT var MATCHES "_DIR$")
            continue()
        endif()
        pkg_is_valid_package_dir_var(dir_var_is_valid "${var}")
        if(NOT dir_var_is_valid)
            continue()
        endif()
        string(REPLACE "\\" "/" dir_value "${${var}}") # Fix windows backslash paths
        file(APPEND ${PKG_INIT_CACHE_FILE}
             "set(${var} [==[${dir_value}]==] CACHE PATH \"Propagated package config directory from parent configure\" FORCE)\n")
    endforeach()
endfunction()


# This function will configure, build and install a package at configure-time
# by running cmake in a subprocess. The current CMake configuration is transmitted
# by setting the flags manually.
function(pkg_install pkg_name)
    set(options DEBUG INSTALL_PREFIX_PKGNAME)
    set(oneValueArgs VERSION INSTALL_DIR INSTALL_SUBDIR BUILD_DIR BUILD_SUBDIR LINK_TYPE)
    set(multiValueArgs HINTS PATHS PATH_SUFFIXES COMPONENTS CMAKE_ARGS LIBRARY_NAMES TARGET_HINTS)
    cmake_parse_arguments(PARSE_ARGV 1 PKG "${options}" "${oneValueArgs}" "${multiValueArgs}")


    # Set directories
    if(NOT PKG_BUILD_DIR)
        set(PKG_BUILD_DIR ${CMAKE_BINARY_DIR}/pkg-build)
    endif()

    if(NOT PKG_INSTALL_DIR)
        if(NOT CMAKE_INSTALL_PREFIX)
            set(PKG_INSTALL_DIR ${CMAKE_BINARY_DIR}/pkg-install)
        else()
            set(PKG_INSTALL_DIR ${CMAKE_INSTALL_PREFIX})
        endif()
    endif()

    pkg_get_lock_file(PKG_LOCK_FILE)
    file(LOCK "${PKG_LOCK_FILE}" GUARD FUNCTION TIMEOUT 600)

    # Append to CMAKE_PREFIX_PATH so we can find the packages later
    pkg_message(DEBUG "Appending to CMAKE_PREFIX_PATH: ${PKG_INSTALL_DIR}")
    list(APPEND CMAKE_PREFIX_PATH ${PKG_INSTALL_DIR})
    pkg_sync_cache_list(CMAKE_PREFIX_PATH "Paths for find_package lookup")
    pkg_sync_cache_list(CMAKE_MODULE_PATH "Paths for find_package module lookup")

    pkg_get_manifest_file(PKG_MANIFEST_FILE "${pkg_name}" "${PKG_INSTALL_DIR}")
    pkg_compute_fingerprint(PKG_FINGERPRINT "${pkg_name}" "${PKG_VERSION}" "${PKG_INSTALL_DIR}" "${PKG_CMAKE_ARGS}")
    pkg_manifest_matches(PKG_MANIFEST_VALID "${PKG_MANIFEST_FILE}" "${PKG_FINGERPRINT}")
    if(PKG_MANIFEST_VALID)
        pkg_message(DEBUG "Already installed: ${pkg_name} (manifest matches ${PKG_MANIFEST_FILE})")
        set(PKG_INSTALL_SUCCESS_${pkg_name} TRUE CACHE BOOL "PKG installed ${pkg_name} successfully in ${PKG_INSTALL_DIR}" FORCE)
        return()
    endif()

    pkg_message(STATUS "${pkg_name} will be installed into ${PKG_INSTALL_DIR}")

    # Generate an init cache to propagate the current configuration
    generate_init_cache()

    # Configure the package
    execute_process(COMMAND  ${CMAKE_COMMAND} -E make_directory ${PKG_BUILD_DIR})
    execute_process(COMMAND  ${CMAKE_COMMAND} -E remove ${PKG_BUILD_DIR}/CMakeCache.txt)
    execute_process(
            COMMAND
            ${CMAKE_COMMAND}
            -Wno-unused-cli
            -C ${PKG_INIT_CACHE_FILE}                # For the subproject in external_<libname>
            -DINIT_CACHE_FILE=${PKG_INIT_CACHE_FILE} # For externalproject_add inside the subproject
            -DCMAKE_INSTALL_PREFIX:PATH=${PKG_INSTALL_DIR}
            -DCMAKE_POLICY_DEFAULT_CMP0074:STRING=NEW # "Honor <PackageName>_ROOT"
            -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW # "Use MSVC_RUNTIME_LIBRARY", fixes spdlog on MSVC
            -DCMAKE_POLICY_DEFAULT_CMP0135:STRING=NEW # "Use DOWNLOAD_EXTRACT_TIMESTAMP"
            -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=TRUE # "Otherwise fails with -G Ninja"
            ${PKG_CMAKE_ARGS}
            ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/external_${pkg_name}
            WORKING_DIRECTORY ${PKG_BUILD_DIR}
            RESULT_VARIABLE config_result
    )
    if(config_result)
        pkg_message(STATUS "Got non-zero exit code while configuring ${pkg_name}")
        pkg_message(STATUS "build_dir             : ${PKG_BUILD_DIR}")
        pkg_message(STATUS "install_dir           : ${PKG_INSTALL_DIR}")
        pkg_message(STATUS "extra_flags           : ${extra_flags}")
        pkg_message(STATUS "config_result         : ${config_result}")
        pkg_message(FATAL_ERROR "Failed to configure ${pkg_name}")
    endif()


    # Make sure to do multithreaded builds if possible
    cmake_host_system_information(RESULT num_threads QUERY NUMBER_OF_PHYSICAL_CORES)


    # Build the package
    if(CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
        # This branch is for multi-config generators such as Visual Studio 16 2019
        foreach(config ${CMAKE_CONFIGURATION_TYPES})
            execute_process(COMMAND  ${CMAKE_COMMAND} --build . --parallel ${num_threads} --config ${config}
                    WORKING_DIRECTORY "${PKG_BUILD_DIR}"
                    RESULT_VARIABLE build_result
                    )
            if(build_result)
                pkg_message(STATUS "Got non-zero exit code while building package: ${pkg_name}")
                pkg_message(STATUS  "build config      : ${config}")
                pkg_message(STATUS  "build dir         : ${PKG_BUILD_DIR}")
                pkg_message(STATUS  "install dir       : ${PKG_INSTALL_DIR}")
                pkg_message(STATUS  "cmake args        : ${PKG_CMAKE_ARGS}")
                pkg_message(STATUS  "build result      : ${build_result}")
                pkg_message(FATAL_ERROR "Failed to build package: ${pkg_name}")
            endif()
        endforeach()
    else()
        # This is for single-config generators such as Unix Makefiles and Ninja
        execute_process(COMMAND  ${CMAKE_COMMAND} --build . --parallel ${num_threads}
                WORKING_DIRECTORY "${PKG_BUILD_DIR}"
                RESULT_VARIABLE build_result
                )
        if(build_result)
            pkg_message(STATUS "Got non-zero exit code while building package: ${pkg_name}")
            pkg_message(STATUS  "build dir         : ${PKG_BUILD_DIR}")
            pkg_message(STATUS  "install dir       : ${PKG_INSTALL_DIR}")
            pkg_message(STATUS  "cmake args        : ${PKG_CMAKE_ARGS}")
            pkg_message(STATUS  "build result      : ${build_result}")
            pkg_message(FATAL_ERROR "Failed to build package: ${pkg_name}")
        endif()
    endif()


    # Copy the install manifest if it exists
    file(GLOB_RECURSE INSTALL_MANIFEST "${PKG_BUILD_DIR}/${pkg_name}/install_manifest*.txt")
    foreach(manifest ${INSTALL_MANIFEST})
        get_filename_component(manifest_filename ${manifest} NAME_WE)
        message(STATUS "Copying install manifest: ${manifest}")
        configure_file(${manifest} ${CMAKE_BINARY_DIR}/${manifest_filename}_${pkg_name}.txt)
    endforeach()
    pkg_write_manifest("${PKG_MANIFEST_FILE}" "${pkg_name}" "${PKG_VERSION}" "${PKG_INSTALL_DIR}" "${PKG_FINGERPRINT}" "${PKG_CMAKE_ARGS}")
    set(PKG_INSTALL_SUCCESS_${pkg_name} TRUE CACHE BOOL "PKG installed ${pkg_name} successfully in ${PKG_INSTALL_DIR}" FORCE)
endfunction()
