if (DMRG_ENABLE_TESTS)
    cmake_minimum_required(VERSION 3.15)
    message(STATUS "Enabling tests")
    enable_testing()
    add_subdirectory(broadcast)
    add_subdirectory(map-shuffle)
    add_subdirectory(partial-trace)
    add_subdirectory(svd)
    add_subdirectory(lbit-evolution)
    add_subdirectory(h5float128)
    if(DMRG_USE_QUADMATH OR DMRG_USE_FLOAT128)
        add_subdirectory(fmtfloat128)
    else()
        message(STATUS "Skipping xdmrg++-test-fmtfloat128: DMRG_USE_QUADMATH and DMRG_USE_FLOAT128 are both disabled")
    endif()
    add_subdirectory(float128_eigen5)
    add_subdirectory(logfloat)
    add_subdirectory(fmtwrappers)
    add_subdirectory(fmtab)
#    add_subdirectory(tomlparser)
    add_subdirectory(toml11parser)
    add_subdirectory(tomlpp_parser)
    add_subdirectory(random)
    add_subdirectory(asScalarType)
    add_subdirectory(qm-regressions)
    add_subdirectory(xdmrg-resume)
    add_subdirectory(enumtraits)
    add_subdirectory(enumgen)
    add_subdirectory(enumcppgen)
endif()
