set(DMRG_CCACHE_ACTIVE FALSE)

if(COMPILER_ENABLE_CCACHE)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "10.0.0")
        message(STATUS "ccache can't be enabled with clang version < 10.0.0")
        return()
    endif()

    find_program(CCACHE_PROGRAM ccache)
    if(CCACHE_PROGRAM)
        foreach(lang C CXX)
            set(launcher_var CMAKE_${lang}_COMPILER_LAUNCHER)
            set(launcher_val "${${launcher_var}}")
            if(launcher_val)
                if(launcher_val MATCHES "(^|;)ccache($|;)")
                    message(STATUS "${launcher_var} already uses ccache: ${launcher_val}")
                    set(DMRG_CCACHE_ACTIVE TRUE)
                else()
                    message(STATUS "Leaving user-defined ${launcher_var} unchanged: ${launcher_val}")
                endif()
            else()
                set(${launcher_var} "${CCACHE_PROGRAM}" CACHE STRING "${lang} compiler launcher" FORCE)
                message(STATUS "Enabling ccache for ${lang} compiler via ${CCACHE_PROGRAM}")
                set(DMRG_CCACHE_ACTIVE TRUE)
            endif()
        endforeach()

        if(COMPILER_ENABLE_PCH AND DMRG_CCACHE_ACTIVE)
            message(STATUS "Detected ccache + pch: remember to set sloppiness = include_file_mtime,pch_defines,time_macros in your ccache config")
        endif()
    else()
        message(STATUS "COMPILER_ENABLE_CCACHE is ON, but no ccache executable was found")
    endif()
endif()
